version: '3'
services:
  todotests:
    image: todotests:latest
    restart: always
    environment:
      FRONT_HOST: todofront
    depends_on:
      - "todofront"
      - "todoback"
  
  todoback:
      image: todobackend:latest
      restart: always
      ports:
        - 3001:3001

  todofront:
    image: todofrontend:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_HOST: todoback
    depends_on:
      - "todoback"    
